### PR TITLE
Adding a new function instructions

### PR DESCRIPTION
**Pull request by webb04**
Document the process of adding a new function

### CODE REVIEW

**Comment by alexduf** [comment]
Is there a way we could ensure that the thriftVersionNumber is updated for each change?

**Comment by davidfurey** [comment]
> Is there a way we could ensure that the thriftVersionNumber is updated for each change?

Yes - https://diwakergupta.github.io/thrift-missing-guide/#_constants

**Comment by alexduf** [comment]
Ha! brilliant.

Another Idea suggested by Jean was to use a way to describe capabilities rather than just using a version. Should we change the version number for a Set of strings that would describe what the implementation is capable of?

If not, then we should use a constant and inject that value on both `webviewThriftVersionNumber` and `nativeThriftVersionNumber`

**Comment by davidfurey** [comment]
Is there any need to define capabilities?  If you call a function that doesn't exist, thrift will return a not implemented exception to the caller.

**Comment by alexduf** [comment]
I see!
I suppose it's not necessary then. Although it might be nice to have a way to test if a function call is supposed to be implemented before trying to call it (for instance if trying to show / hide some component)

**Comment by webb04** [comment]
Made a ticket for that, guess it would involve adding to the shell script to make that constant the same as the latest GIthub tag.

**Pull request merged**
